### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bonesmaxx1991**
keep on finding the R file for exec the R command.

### CODE REVIEW

**Comment by bonesmaxx1991** [comment]
We fix this by changing the`./configure` to `./configure --without-pic --disable-shared`. Then, it came to R language using problem.So we are figuring out the PATH for R now and rebuild the compile file again. Because we find the paths are so complicated and all the files compile on the folder of `"/home/vcap"`.And we need more time to figure it out.And we believe that all the problems caused by unnecessary memory used and timeout. So problems show like that:

**Comment by bonesmaxx1991** [comment]
Base your question in the last mail,we try the different compiles and the outcomes are different.
And this the compile we make and it called compile_GSC, you need to change its name to compile, commit to master and sync the code. And run the cf push again and you will see the result in gsc.txt.
Problems show in log:

```
2016-08-12T10:56:56.20+0800 [STG/0]      OUT R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
2016-08-12T10:56:56.20+0800 [STG/0]      OUT Copyright (C) 2016 The R Foundation for Statistical Computing
2016-08-12T10:56:56.20+0800 [STG/0]      OUT Platform: x86_64-pc-linux-gnu (64-bit)
2016-08-12T10:56:56.20+0800 [STG/0]      OUT R is free software and comes with ABSOLUTELY NO WARRANTY.
2016-08-12T10:56:56.20+0800 [STG/0]      OUT You are welcome to redistribute it under the terms of the
2016-08-12T10:56:56.20+0800 [STG/0]      OUT GNU General Public License versions 2 or 3.
2016-08-12T10:56:56.20+0800 [STG/0]      OUT For more information about these matters see
2016-08-12T10:56:56.20+0800 [STG/0]      OUT http://www.gnu.org/licenses/.
2016-08-12T10:56:56.22+0800 [STG/0]      OUT        Fatal error: unable to open the base package
2016-08-12T10:56:56.23+0800 [STG/0]      OUT R CMD-FINISH
2016-08-12T10:56:56.89+0800 [STG/35]    OUT -----> Uploading droplet (2.0M)
2016-08-12T10:57:10.00+0800 [API/1]      ERR encountered error: Staging error: failed to stage application:
2016-08-12T10:57:43.02+0800 [DEA/35]    OUT Starting app instance (index 0) with guid da7a038c-5ab5-4ec9-a0a8-
```

This is the log file which contain the information shows that the R is successfully installed.
    But  unfortunately the server for mpc is not work today：
    And we are find out the way to use R to run init.r script or some simple R codes and other source for dependencies in gfortran. If you have any ideas to run the init.r or R codes in compile successfully, please let us know.

**Comment by rddill-IBM** [comment]
The gnu.org site went down last night and has not yet come back on line. Our builds, which are dependent on this site, are inoperable until it comes back on line. I will check results again after gnu.org is available.

**Comment by bonesmaxx1991** [comment]
# On the cloud foundry

we test the compile code with `CF_STAGING_TIMEOUT: 30` many times and staging were failed. Here are the output txt you can see:
     You can see the failed points are different, 
[To-bob1.txt](https://github.com/rddill-IBM/BlueMix-R-Buildpack/files/419910/To-bob1.txt)
[To-bob2.txt](https://github.com/rddill-IBM/BlueMix-R-Buildpack/files/419911/To-bob2.txt)
and we think it is **out of memory** to install all the dependencies.
And after we add `CF_STAGING_TIMEOUT: 30` , the whole process ran about 20 minutes.

# On the virtual machine

We ran the **compile** and **compile_GSC** separately on different virtual machine. we fix the problem by writing the right **PATH**.

```
checking for dummy main to link with Fortran libraries... unknown
 configure: error: linking to Fortran libraries from C fails
```

we add the code:

```
export LIBRARY_PATH="/lib:/usr/lib:/usr/lib/x86_64-linux-gnu:/home/ibm/gccF/lib64"
export LD_LIBRARY_PATH=":/home/ibm/gccF/lib:/home/ibm/gccF/lib64"
export FLIBS="-L/lib -L/usr/lib -L/usr/lib64 -L/usr/lib/x86_64-linux-gnu -L/home/ibm/gccF/lib64 -L/home/ibm/gccF/bin”
```

when we use`./configure --prefix=/home/ibm/R --with-readline=no --with-x=no`under `/R-3.3.1` the problems show:
`checking whether zlib support suffices... configure: error: zlib library and headers are required
`we work with the reference:[http://pj.freefaculty.org/blog/?p=315](http://pj.freefaculty.org/blog/?p=315) to solve the problems step by step and .
And we think the missing packages and dependencies in the blog are installed successfully on cloud foundry. And if the they shows just follow the guide till them solve.
Shan focus on replicate your compile and export the right PATH and fix the problems on virtual machine. Zhe work on virtual machine and finds out the problem of out of memory(**the highest point 16G in memory**). And I help to test on cloud foundry.
     Here is the script we use to successfully to install the dependencies and R on virtual machine called VMscript.txt
[VMscript.txt](https://github.com/rddill-IBM/BlueMix-R-Buildpack/files/419920/VMscript.txt)
We think if there are enough memory, the compile will successfully install. But the memory and time limit problems we can’t solve.

**Comment by bonesmaxx1991** [comment]
# On cloud foundry

We test for many times and the failed points are different in gcc make -j. The cause is cannot allocate memory. here are the log txt and key logs.
[virtaulmachineFORcf1.txt](https://github.com/rddill-IBM/BlueMix-R-Buildpack/files/422459/virtaulmachineFORcf1.txt)

```
from ../.././gcc/basic-block.h:25,
from ../.././gcc/graphite-sese-to-poly.c:43:
./tm.h:25:30: error: ../.././gcc/config/i386/att.h: Cannot allocate memory
./tm.h:26:28: error: ../.././gcc/config/dbxelf.h: Cannot allocate memory
./tm.h:35:39: error: ../.././gcc/config/i386/linux-common.h: Cannot allocate memory
./tm.h:36:34: error: ../.././gcc/config/i386/linux64.h: Cannot allocate memory
```

[virtaulmachineFORcf2.txt](https://github.com/rddill-IBM/BlueMix-R-Buildpack/files/422461/virtaulmachineFORcf2.txt)

```
In file included from ../.././gcc/emit-rtl.c:35:0:
../.././gcc/system.h:647:17: error: /home/vcap/app/gcc/include/gmp.h: Cannot allocate memory
../.././gcc/system.h:651:23: error: ../.././gcc/../include/libiberty.h: Cannot allocate memory
In file included from ../.././gcc/system.h:647:0,
 from ../.././gcc/hw-doloop.c:22:
/home/vcap/app/gcc/include/gmp.h:34:70: error: /usr/include/c++/4.8/iosfwd: Cannot allocate memory
#include <iosfwd>   /* for std::istream, std::ostream, std::string */
                                                                   ^
In file included from ../.././gcc/omega.c:34:0:
../.././gcc/system.h:494:22: error: /usr/include/inttypes.h: Bad address
#include <inttypes.h>
              ^
In file included from ../.././gcc/emit-rtl.c:37:0:
./tm.h:19:22: error: ./options.h: Bad address
# include "options.h"
                ^
make[3]: *** Deleting file `symtab.o'
```

The cloud foundry test memory is 4G which is the large memory on bluemix. 

# On virtual machine test

We use the same script to install the dependencies and deploy the PATH on the virtual machine(Ubuntu 14.04) and the installation is successful. 
And here are the outcome and the script file:

```
R version 3.3.1 (2016-06-21) — "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

>   print("=====HHH+++++")
[1] "=====HHH+++++"
>   a<-c(1:20)
>   b<-c(1:4)
>   c<-a/b
>   data<-data.frame(a,b,c)
>   write.table(data,file="/home/ibm/data2",row.names=FALSE)
    >   q()
```

[VMscript.txt](https://github.com/rddill-IBM/BlueMix-R-Buildpack/files/422467/VMscript.txt)
Here is the script for installation on virtual machine. 
The outcomes means R is successfully installed manually. But we can not fix the problem of cannot allocate memory, because we can not raise the memory of cloud foundry.

**Comment by bonesmaxx1991** [comment]
Today we found a useful buildpack which combine the dependencies and R installation pack together. And you can try on this link:[https://github.com/bonesmaxx1991/BlueMix-R-Buildpack.git](https://github.com/bonesmaxx1991/BlueMix-R-Buildpack.git)

# On cloud foundry

We try this:`CF_STAGING_TIMEOUT=30 TRACE=YES cf push IBMCSA -b https://github.com/bonesmaxx1991/BlueMix-R-Buildpack.git -n IBMCSA >cf-heroku.txt`
The script is too big and you can find it on the mail.
The process of installation failed in R making without no clear reasons. So to confirm the real reason, we will test the compile on virtual machine.

# On virtual machine

We test the script we push to you again. The whole installation is about 3 hours or more. And sometime the memory excess 4 G which it cause the CF installation failed and the export path is only work in compile installation which may not be the problem for CF.

**Pull request merged**
